name: Python Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        run: actions/setup-python@v5
        with:
          python-version: 3.5
      - name: Run python script
        run: python app.py
